export enum TYPES {
    FETCH_START = 'FETCH_START',
    FETCH_LOADING = 'FETCH_LOADING',
    FETCH_ORIGINAL_LIST = 'FETCH_ORIGINAL_LIST',
    FETCH_SORT_LIST = 'FETCH_SORT_LIST',
    FETCH_SORT_TYPE = 'FETCH_SORT_TYPE',
    FETCH_SEARCH = 'FETCH_SEARCH'
};